### ISSUE TITLE
Problem with latest version of torch?

### ISSUE THREAD

**Issue by aobertas** [dtamayo/spock#21]
Using python 3.10.2, torch 2.0.0

`>>> from spock import FeatureClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fs/lustre/scratch/RAID-CITA/obertas/venv-apr-2023-3.10.2/lib/python3.10/site-packages/spock/__init__.py", line 5, in <module>
    from .deepregressor import DeepRegressor
  File "/fs/lustre/scratch/RAID-CITA/obertas/venv-apr-2023-3.10.2/lib/python3.10/site-packages/spock/deepregressor.py", line 14, in <module>
    from .spock_reg_model import load_swag
  File "/fs/lustre/scratch/RAID-CITA/obertas/venv-apr-2023-3.10.2/lib/python3.10/site-packages/spock/spock_reg_model.py", line 19, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'`

**Comment by MilesCranmer** [comment]
This should fix it: https://github.com/dtamayo/spock/pull/22. Let me know if it doesn't work,

Thanks!
Miles

**Comment by aobertas** [comment]
Thanks for getting a fix super quickly!
